2025-06-26 08:12:27,477 - INFO - logging configured by default settings
DEBUG: Checking if FetchFundingOpportunities(max_pages=None, page_size=50, output_file=calls_raw.json) is complete
2025-06-26 08:12:27,483 - DEBUG - Checking if FetchFundingOpportunities(max_pages=None, page_size=50, output_file=calls_raw.json) is complete
INFO: Informed scheduler that task   FetchFundingOpportunities_None_calls_raw_json_50_8fc9b45bdb   has status   PENDING
2025-06-26 08:12:27,483 - INFO - Informed scheduler that task   FetchFundingOpportunities_None_calls_raw_json_50_8fc9b45bdb   has status   PENDING
INFO: Done scheduling tasks
2025-06-26 08:12:27,484 - INFO - Done scheduling tasks
INFO: Running Worker with 1 processes
2025-06-26 08:12:27,484 - INFO - Running Worker with 1 processes
DEBUG: Asking scheduler for work...
2025-06-26 08:12:27,484 - DEBUG - Asking scheduler for work...
DEBUG: Pending tasks: 1
2025-06-26 08:12:27,484 - DEBUG - Pending tasks: 1
INFO: [pid 1419407] Worker Worker(salt=9377629313, workers=1, host=ip-10-0-1-46, username=ubuntu, pid=1419407) running   FetchFundingOpportunities(max_pages=None, page_size=50, output_file=calls_raw.json)
2025-06-26 08:12:27,484 - INFO - [pid 1419407] Worker Worker(salt=9377629313, workers=1, host=ip-10-0-1-46, username=ubuntu, pid=1419407) running   FetchFundingOpportunities(max_pages=None, page_size=50, output_file=calls_raw.json)
2025-06-26 08:12:27,708 - ERROR - Fatal error in scraping process: Message: session not created
from unknown error: no chrome binary at /usr/bin/chromium
Stacktrace:
#0 0x59f1c4ea667a <unknown>
#1 0x59f1c4972cd0 <unknown>
#2 0x59f1c49a9947 <unknown>
#3 0x59f1c49a7d58 <unknown>
#4 0x59f1c49f7464 <unknown>
#5 0x59f1c49f6b86 <unknown>
#6 0x59f1c49e89f3 <unknown>
#7 0x59f1c49b5534 <unknown>
#8 0x59f1c49b6191 <unknown>
#9 0x59f1c4e6deef <unknown>
#10 0x59f1c4e71f98 <unknown>
#11 0x59f1c4e550f2 <unknown>
#12 0x59f1c4e7273e <unknown>
#13 0x59f1c4e3c0be <unknown>
#14 0x59f1c4e94c68 <unknown>
#15 0x59f1c4e94e78 <unknown>
#16 0x59f1c4ea511c <unknown>
#17 0x7aaa29142ac3 <unknown>

ERROR: [pid 1419407] Worker Worker(salt=9377629313, workers=1, host=ip-10-0-1-46, username=ubuntu, pid=1419407) failed    FetchFundingOpportunities(max_pages=None, page_size=50, output_file=calls_raw.json)
Traceback (most recent call last):
  File "/home/ubuntu/CallsForProposals/eu_funding_pipeline_extractScript/tasks/.venv/lib/python3.12/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/CallsForProposals/eu_funding_pipeline_extractScript/tasks/.venv/lib/python3.12/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
               ^^^^^^^^^^^^^^^
  File "/home/ubuntu/CallsForProposals/eu_funding_pipeline_extractScript/tasks/extract.py", line 591, in run
    scraper.setup_driver()
  File "/home/ubuntu/CallsForProposals/eu_funding_pipeline_extractScript/tasks/extract.py", line 51, in setup_driver
    self.driver = webdriver.Chrome(service=service, options=chrome_options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/CallsForProposals/eu_funding_pipeline_extractScript/tasks/.venv/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    super().__init__(
  File "/home/ubuntu/CallsForProposals/eu_funding_pipeline_extractScript/tasks/.venv/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 69, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/ubuntu/CallsForProposals/eu_funding_pipeline_extractScript/tasks/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 257, in __init__
    self.start_session(capabilities)
  File "/home/ubuntu/CallsForProposals/eu_funding_pipeline_extractScript/tasks/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/CallsForProposals/eu_funding_pipeline_extractScript/tasks/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 447, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/CallsForProposals/eu_funding_pipeline_extractScript/tasks/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from unknown error: no chrome binary at /usr/bin/chromium
Stacktrace:
#0 0x59f1c4ea667a <unknown>
#1 0x59f1c4972cd0 <unknown>
#2 0x59f1c49a9947 <unknown>
#3 0x59f1c49a7d58 <unknown>
#4 0x59f1c49f7464 <unknown>
#5 0x59f1c49f6b86 <unknown>
#6 0x59f1c49e89f3 <unknown>
#7 0x59f1c49b5534 <unknown>
#8 0x59f1c49b6191 <unknown>
#9 0x59f1c4e6deef <unknown>
#10 0x59f1c4e71f98 <unknown>
#11 0x59f1c4e550f2 <unknown>
#12 0x59f1c4e7273e <unknown>
#13 0x59f1c4e3c0be <unknown>
#14 0x59f1c4e94c68 <unknown>
#15 0x59f1c4e94e78 <unknown>
#16 0x59f1c4ea511c <unknown>
#17 0x7aaa29142ac3 <unknown>

2025-06-26 08:12:27,708 - ERROR - [pid 1419407] Worker Worker(salt=9377629313, workers=1, host=ip-10-0-1-46, username=ubuntu, pid=1419407) failed    FetchFundingOpportunities(max_pages=None, page_size=50, output_file=calls_raw.json)
Traceback (most recent call last):
  File "/home/ubuntu/CallsForProposals/eu_funding_pipeline_extractScript/tasks/.venv/lib/python3.12/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/CallsForProposals/eu_funding_pipeline_extractScript/tasks/.venv/lib/python3.12/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
               ^^^^^^^^^^^^^^^
  File "/home/ubuntu/CallsForProposals/eu_funding_pipeline_extractScript/tasks/extract.py", line 591, in run
    scraper.setup_driver()
  File "/home/ubuntu/CallsForProposals/eu_funding_pipeline_extractScript/tasks/extract.py", line 51, in setup_driver
    self.driver = webdriver.Chrome(service=service, options=chrome_options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/CallsForProposals/eu_funding_pipeline_extractScript/tasks/.venv/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    super().__init__(
  File "/home/ubuntu/CallsForProposals/eu_funding_pipeline_extractScript/tasks/.venv/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 69, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/ubuntu/CallsForProposals/eu_funding_pipeline_extractScript/tasks/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 257, in __init__
    self.start_session(capabilities)
  File "/home/ubuntu/CallsForProposals/eu_funding_pipeline_extractScript/tasks/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/CallsForProposals/eu_funding_pipeline_extractScript/tasks/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 447, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/CallsForProposals/eu_funding_pipeline_extractScript/tasks/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from unknown error: no chrome binary at /usr/bin/chromium
Stacktrace:
#0 0x59f1c4ea667a <unknown>
#1 0x59f1c4972cd0 <unknown>
#2 0x59f1c49a9947 <unknown>
#3 0x59f1c49a7d58 <unknown>
#4 0x59f1c49f7464 <unknown>
#5 0x59f1c49f6b86 <unknown>
#6 0x59f1c49e89f3 <unknown>
#7 0x59f1c49b5534 <unknown>
#8 0x59f1c49b6191 <unknown>
#9 0x59f1c4e6deef <unknown>
#10 0x59f1c4e71f98 <unknown>
#11 0x59f1c4e550f2 <unknown>
#12 0x59f1c4e7273e <unknown>
#13 0x59f1c4e3c0be <unknown>
#14 0x59f1c4e94c68 <unknown>
#15 0x59f1c4e94e78 <unknown>
#16 0x59f1c4ea511c <unknown>
#17 0x7aaa29142ac3 <unknown>

DEBUG: 1 running tasks, waiting for next task to finish
2025-06-26 08:12:27,712 - DEBUG - 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   FetchFundingOpportunities_None_calls_raw_json_50_8fc9b45bdb   has status   FAILED
2025-06-26 08:12:27,715 - INFO - Informed scheduler that task   FetchFundingOpportunities_None_calls_raw_json_50_8fc9b45bdb   has status   FAILED
DEBUG: Asking scheduler for work...
2025-06-26 08:12:27,715 - DEBUG - Asking scheduler for work...
DEBUG: Done
2025-06-26 08:12:27,716 - DEBUG - Done
DEBUG: There are no more tasks to run at this time
2025-06-26 08:12:27,716 - DEBUG - There are no more tasks to run at this time
DEBUG: There are 1 pending tasks possibly being run by other workers
2025-06-26 08:12:27,716 - DEBUG - There are 1 pending tasks possibly being run by other workers
DEBUG: There are 1 pending tasks unique to this worker
2025-06-26 08:12:27,716 - DEBUG - There are 1 pending tasks unique to this worker
DEBUG: There are 1 pending tasks last scheduled by this worker
2025-06-26 08:12:27,716 - DEBUG - There are 1 pending tasks last scheduled by this worker
INFO: Worker Worker(salt=9377629313, workers=1, host=ip-10-0-1-46, username=ubuntu, pid=1419407) was stopped. Shutting down Keep-Alive thread
2025-06-26 08:12:27,716 - INFO - Worker Worker(salt=9377629313, workers=1, host=ip-10-0-1-46, username=ubuntu, pid=1419407) was stopped. Shutting down Keep-Alive thread
INFO: 
===== Luigi Execution Summary =====

Scheduled 1 tasks of which:
* 1 failed:
    - 1 FetchFundingOpportunities(max_pages=None, page_size=50, output_file=calls_raw.json)

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

2025-06-26 08:12:27,717 - INFO - 
===== Luigi Execution Summary =====

Scheduled 1 tasks of which:
* 1 failed:
    - 1 FetchFundingOpportunities(max_pages=None, page_size=50, output_file=calls_raw.json)

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

